spring:
  application:
    name: sharenest-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://gangwars:Tog0nFk3GXuVorA4@cluster0.hhcnyf2.mongodb.net/sharenest?retryWrites=true&w=majority&appName=NewNest}
  jackson:
    serialization:
      write-dates-as-timestamps: false

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:duh4hgrhy}
  api_key: ${CLOUDINARY_API_KEY:373679537749362}
  api_secret: ${CLOUDINARY_API_SECRET:70PbAwOzvQDmoy4LReNx1HZRXnM}

jwt:
  secret: ${JWT_SECRET:b8a2871fe35d4a28b2789e6ffd52ffb4d97d4e125c34e98f572b35efbb12c80d}
  expiration: 86400000  # 24h in ms

logging:
  level:
    root: INFO
    com.gangwarsatyam.sharenest: DEBUG

server:
  port: ${PORT:8080}
